import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Header from "./components/main/Header";
import Footer from "./components/main/Footer";
import ContactsLinks from "./components/main/ContactsLinks";
import { StickyProvider } from "@/lib/context/Store";
import CursorPointer from "./components/pieces/CursorPointer";
import ScrollTopButton from "./components/pieces/ScrollTopButton";

const geistSans = Cairo({
  variable: "--font_cairo",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Two Stars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${geistSans.variable} antialiased`}>
        <StickyProvider>
          <CursorPointer />
          <ScrollTopButton />
          <Header />
          <ContactsLinks />
          <main className="relative top-0 left-0">{children}</main>
          <Footer />
        </StickyProvider>
      </body>
    </html>
  );
}
